version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
  backend:
    image: aldrinm/hello-spring:0.0.1
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_CORS_ORIGINS=${ALLOWED_CORS_ORIGINS}
  frontend:
    image: aldrinm/hello-angular:0.0.0
    ports:
      - "8180:80"
      